---
editor: visual
author: "Karolina Molisak, Maurycy Żarczyński"
format:
  html:
    toc: true
    toc-title: Etapy
    toc-depth: 4
    embed-resources: true
  pdf:
    geometry: 
    - top=20mm
    - left=20mm
    - bottom=20mm
    - right=20mm
theme:
  light: flatly
  dark: darkly
---

# CNS: Przygotowanie próbek

-   Włączyć wagę analityczną.

    Waga powinna zostać włączona przynajmniej godzinę przed przewidywaną pracą.

-   Włączyć komputer.

-   Włączyć program Vario El Cube.

    Skrót znajduje się na pasku zadań.

-   Otworzyć plik z danymi. Uzupełnić nazwę próbki oraz symbol rynienki.

-   Pobrać kapsułkę cynową. Ustawić na wadze i wytarować.

-   Umieścić kapsułkę w metalowej formie, lekko docisnąć, można ewentualnie odgiąć boki, celem łatwiejszego nakładania próbki.

-   Mikrołyżeczką nabrać osad i wsypać odpowiednią ilość, około **20 mg** ± **3 mg**.

    | Masa osadu ustalona dla przeważnie analizowanej gytii jeziornej. W przypadku innych osadów należy najpierw wykonać oznaczenia testowe na reprezentatywnych próbkach.

-   Sprawdzić masę próbki.

    | Przed włożeniem do wagi lekko obstukać kapsułkę, aby usunąć ewentualny osad znajdujący się na zewnątrz.

-   Zapakować próbkę. Zacisnąć od góry pęsetą, pozbywając się jak największej ilości powietrza. Następnie specjalnym narzędziem docisnąć próbkę kilkukrotnie.

    | Obecność powietrze wpływa na wyniki analizy, zwłaszcza oznaczenia koncentracji azotu.

-   Zawinąć brzegi próbki dwukrotnie.

-   Uformować za pomocą pęset sześcian.

-   Przed włożeniem do wagi sprawdzić czy osad nie wysypuje się z próbki. Obstukać sześcian.

    | Jeżeli nie dochodzi do wysypywania, można przystąpić do ważenia. Jeżeli osad się wysypuje, próbkę należy przygotować ponownie.

-   Zważyć próbkę i nacisnąć ikonę druku, wówczas waga prześle masę do komputera.

-   Umieścić sześcian w odpowiedniej rynience w pojemniku.

-   Wyczyścić narzędzia alkoholem.

{{< pagebreak >}}

## Rejestr zmian

-   01.12.2022 MZ: wersja inicjalna Quarto. Rozwinięcie treści.
-   28.05.2023 MZ: Quarto book chapter.
