---
editor: visual
author: "Wojciech Tylmann, Karolina Molisak, Maurycy Żarczyński"
format:
  html:
    toc: true
    toc-title: Etapy
    toc-depth: 4
    embed-resources: true
  pdf:
    geometry: 
    - top=20mm
    - left=20mm
    - bottom=20mm
    - right=20mm
theme:
  light: flatly
  dark: darkly
---

# Raportowanie: spektrometr gamma

## Praca z oprogramowaniem

-   Otworzyć plik z wybranym widmem.

-   Z paska menu przejść do **kalibracji**:

    | `Calibrate > Load`

    -   Zaznaczyć **Energy**, odznaczyć **Efficiency.**

        -   Wybrać plik z rozszerzeniem `*.energy`, kliknąć dwukrotnie.

-   Z paska manu przejść do **kalibracji**:

    | `Calibrate > Load`

    -   Zaznaczyć **Efficiency**.

    -   Wybrać plik z rozszerzeniem `*.efficiency`, kliknąć dwukrotnie.

-   Z paska manu przejść do analizy:

    | `Analyze > Execute Sequence > ECR_lab…`

    -   W oknie wypełnić obowiązkowe pola:
        -   Nazwę próbki oraz ID w formacie: 3 pierwsze litery jeziora (bez polskich znaków)

        -   Rok poboru rdzenia.

        -   Numer rdzenia.

        -   Kolejny nr próbki, z rozwinięciem poprzedzonym odpowiednią liczbą zer.

            | JJJ_18-2\_**01**

        -   Masę próbki[^gamma-report_pl-1].

            Zatwierdzić `OK`.

-   Na widmie powinny pojawić się symbole izotopów.

    Raport automatycznie zapisuje się na dysku.

-   Zamknąć widmo.

    > **Nie zapisywać zmian.**

-   Przejść do kolejnej próbki i powtórzyć powyższe kroki.

-   Przejść do lokalizacji *C:\\GENIE2K\\CAMFILES\\REPFILES* i odnaleźć plik z widmem.

-   Utworzyć nowy katalog dla kolejnego rdzenia osadów i przenieść tam dokumenty.

-   Wykonać kopię zapasową plików z wykorzystaniem programu `DSynchronize`.

[^gamma-report_pl-1]: Separator dziesiętny to kropka.

## Rejestr zmian

-   01.12.2022 MZ: wersja inicjalna Quarto. Rozwinięcie treści.
-   28.05.2023 MZ: Quarto book chapter.
