---
editor: visual
author: "Karolina Molisak, Maurycy Żarczyński"
format:
  html:
    toc: true
    toc-title: Etapy
    toc-depth: 4
    embed-resources: true
  pdf:
    geometry: 
    - top=20mm
    - left=20mm
    - bottom=20mm
    - right=20mm
theme:
  light: flatly
  dark: darkly
---

# Uzupełnianie ciekłego azotu i wymiana próbki w spektrometrze gamma

## Uzupełnianie ciekłego azotu

### Dzień pierwszy

-   Zamontować kran na dewarze, dokręcić zawór boczny i zabezpieczyć kran stalową linką.

-   Poczekać kilka godzin do wzrostu ciśnienia w dewarze.

-   Włączyć komputer i otworzyć detektor.

-   Zapytanie:

    | Trwa pomiar, czy chcesz mimo to otworzyć: `Tak`.

-   Zapytanie:

    | Czy przerwać pomiar: `Nie`.

-   W lewym górnym rogu przerwać pomiar:

    | `Stop`.

-   Odkręcić górny zawór (czarny).

-   Przelać część azotu.

-   Zamknąć zawór górny (czarny).

-   Wznowić analizę próbki po upływie około **15--20 minut**.

    Detektor potrzebuje czasu na ponowną stabilizację.

### Dzień drugi

-   Włączyć komputer i otworzyć detektor.

-   Zatrzymać analizę próbki, zgodnie z instrukcją powyżej.

-   Odkręcić górny zawór (czarny).

-   Przelać azot aż do wyraźnego wycieku z węża odprowadzającego.

-   Zamknąć zawór górny (czarny).

-   Wznowić analizę próbki po upływie **15--20 minut**.

-   Po upływie okokło **1 h**, gdy temperatura wzrośnie zdemontować kran.

    W tym celu, odkręcić zawór boczny, stabilizując ciśnienie, następnie zdemontować kran, uważając by nie skaleczyć dłoni o ostre krawędzie.

-   Zamknąć dewar i umieścić w chłodni.

-   Jeżeli nie został przelany cały azot, przed kolejną dostawą, dolać pozostałość.

> Zapisać dzień, w którym poborano azot z Wydziału Chemii wraz z wagą w pliku `.xlsx` na serwerze.
>
> Odnotować w kalendarzu dzień, w którym przelewano azot oraz czy doszło do przelania.

## Zmiana próbki w spektrometrze

-   Włączyć komputer i otworzyć detektor.

-   Po skończonym pomiarze nadpisać plik:

    | `File > Save as` i wybrać próbkę z listy.

-   Wyczyścić bieżące widmo:

    | `Clear`.

-   Wymienić próbkę w detektorze.

-   Uruchomić pomiar:

    | `Start`.

-   Zapisać próbkę

    | `File > Save as`.

-   Zamknąć program.

-   Wykonać kopię zapasową plików z wykorzystaniem programu `DSynchronize`.

-   Wyłączyć komputer.

## Rejestr zmian

-   01.12.2022 MZ: wersja inicjalna Quarto. Rozwinięcie treści.
-   28.05.2023 MZ: Quarto book chapter.

