---
editor: visual
author: "Wojciech Tylmann, Alicja Bonk, Karolina Molisak, Maurycy Żarczyński"
lang: pl
format:
  html:
    toc: true
    toc-title: Etapy
    toc-depth: 4
    embed-resources: true
  pdf:
    geometry: 
    - top=20mm
    - left=20mm
    - bottom=20mm
    - right=20mm
theme:
  light: flatly
  dark: darkly
---

# Przygotowanie preparatów rozmazowych

### Przygotowanie stanowiska

-   Ustalić regularne interwały poboru próbek, w zależności od długości rdzenia, z uwzględnieniem dodatkowych próbek z miejsc charakterystycznych (np. próbka z laminy jasnej i ciemnej).
-   Przygotować:
    -   Szkiełka podstawowe.
    -   Szkiełka nakrywkowe.
    -   Wodę dejonizowaną.
    -   Alkohol etylowy.
    -   Klej światłoutwardzalny **Drei Bond 6020** (gęstszy) oraz **6023** (rzadszy).
    -   Szpatułkę.
    -   Pęsetę.
    -   Etykiety.
    -   Etui kartonowe na preparaty.
    -   Płytę grzejną.
    -   Źródło promieniowania UV.
-   Szkiełka podstawowe należy umyć wodą lub alkoholem, a następnie dokładnie wytrzeć. Podpisać etykietę na szkiełku podstawowym wg schematu:
    -   Rdzeń: `JJJ-RR/N–S XX`:

        **JJJ**: stanowisko, **RR**: rok poboru, **N**: nr rdzenia, **S**: nr sekcji, **XX**: odległość od stropu w danej sekcji.

        | Jeśli pobierana jest próbka z laminy jasnej i ciemnej na jedno szkiełko podstawowe, opisać dodatkowo uwagi lub przyczyny wykonania danej próbki w dokumentacji (np. tefra, barwa, wcześniejsze potraktowanie osadu HCl).

    -   Materiał z pułapki sedymentacyjnej: `JJJ RRRR-MM-DD TYP`:

        **JJJ**: stanowisko, **RRRR**: rok, **MM**: miesiąc, **DD**: dzień, **TYP**: **H** (hypolimnion) lub **M** (metalimnion).

## Przygotowanie preparatu

::: callout-warning
## Promieniowanie UV

Nie patrzeć bezpośrednio w źródło promieniowania UV. Wiązanie zachodzi z obudowanej skrzyni z lampą uv.

Unikać kontaktu skóry z klejem Drei Bond. Pracować w rękawiczkach, po skończeniu pracy dokładnie umyć ręce.
:::

-   Za pomocą szpatułki pobrać niewielką ilość osadu i umieścić na szkiełku podstawowym.

    | Materiał powinien być rozłożony równomiernie, unikając zagęszczenia, ponieważ utrudni to analizę preparatu.

-   Do osadu umieszczonego na szkiełku dodać za pomocą pipety kroplę wody dejonizowanej lub alkoholu. Rozprowadzić osad dokładnie przy pomocy szpatułki lub wykałaczki.

-   Na płycie grzejnej rozgrzanej do **60--70 °C** umieścić szkiełko podstawowe. Pozostawić do momentu, aż woda całkowicie odparuje, a osad będzie zupełnie suchy: około **2--5 minut**.

-   Zdjąć szkiełko podstawowe z płyty grzejnej, na wysuszony osad dodać kroplę **Drei Bond** i przy pomocy pęsety delikatnie nałożyć na wierzch szkiełko nakrywkowe.

-   Umieścić preparat w etui kartonowym lub na tekturze i poddać działaniu **promieniowania UV** przez około **1--2 minuty**.

    | Na koniec należy sprawdzić, czy szkiełko nakrywkowe zostało prawidłowo przyklejone.

-   Preparaty należy przechowywać w przeznaczonych do tego celu opakowaniach.

{{< pagebreak >}}

## Rejestr zmian

-   03.12.2022 MZ: wersja inicjalna Quarto. Rozwinięcie treści.
-   29.05.2023 MZ: Quarto book chapter.
